compatible: "zmk,behavior-modquad"
description: Custom behavior that outputs different keycodes based on modifier state
include: "behavior.yaml"

properties:
  bindings:
    type: phandle-array
    required: true
    description: |
      List of key behaviors:
      1. no modifiers
      2. shift
      3. altgr
      4. shift+altgr
