name: Build ZMK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ZMK
        uses: zmkfirmware/zmk-docker-build@stable
        with:
          board: "nice_nano_v2"
          shield: "sofle_left sofle_right"
          zmk-config: "config"
          build-args: |
            -DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE/config
            -DCONFIG_ZMK_BUILD_COPY_CUSTOM_BINDINGS=y
